### ISSUE TITLE
Can you make it work in Wordpress?

### ISSUE THREAD

**Issue by rudeamy** [lfarrell/DPLA-Search-Widget#5]
It'd be great to be able to install this on Wordpress. However, because the general user doesn't have access to the header text, they can't.

**Comment by lfarrell** [comment]
As a WP plugin?

**Comment by rudeamy** [comment]
Yeah, a widget.

**Comment by lfarrell** [comment]
What should work is have the user create a new page or edit an existing
page in WP and then just make sure to include the JS file below the

<div id="dpla_search_widget"></div> line like so.
<div id="dpla_search_widget"></div>

<script type="text/javascript" src="dpla-search-widget.js"></script>

It's not the ideal way to add JS to WP, but should work.  Ideally the user
would enqueue the js file in their template.

**Comment by lfarrell** [comment]
Should be fixed now.  See https://github.com/lfarrell/Wordpress-DPLA-Search-Widget-Plugin.
